[package]
name = "hanower"
version = "0.2.1"
authors = ["emucc <github@elrimer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
anyhow = "1.0"
