name: Quick Continuous Integration

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  # Check code paths touched by incoming changes
  diff:
    runs-on: ubuntu-latest
    outputs:
      cli: ${{ steps.filter.outputs.cli }}
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cli:
              - 'cli/**'
            core:
              - 'core/**'

  quick-ci:
    needs: diff
    runs-on: ubuntu-18.04
    env:
      CORE_ONLY: "${{ needs.diff.outputs.core == 'true' && needs.diff.outputs.cli == 'false' }}"
      TEST_CARGO_ARGS: "${{ env.CORE_ONLY == 'true' && '--lib' || '' }}"
    steps:
      - run: env

      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Code check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: ${{ env.CORE_ONLY == 'true' && '--lib' || ''}}

      - name: Code test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ env.CORE_ONLY == 'true' && '--lib' || ''}}

      - name: Code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
